In [2]:
def test():
    return 0
#test

In [2]:
import numpy as np

# Assuming you have the data stored as NumPy arrays or lists
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data2 = np.array([[4, 5, 6], [10, 11, 12]])

# Extract the columns 2 and 3 from data and data2
data_subset = data[:, 1:3]
data2_subset = data2[:, 1:3]

# Check if the rows in data_subset exist in data2_subset
mask = np.isin(data_subset, data2_subset)

# Filter the rows in data using the mask
result = data[mask[:, 0] & mask[:, 1]]

print(result)


[[4 5 6]]


In [3]:
data, data2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]]))

In [8]:
data_subset, data2_subset

(array([[2, 3],
        [5, 6],
        [8, 9]]),
 array([[ 5,  6],
        [11, 12]]))

In [11]:
mask

array([[False, False],
       [ True,  True],
       [False, False]])

In [15]:
import heapq

min_heap = []

heapq.heappush(min_heap, 4)
heapq.heappush(min_heap, 1)
heapq.heappush(min_heap, 7)
heapq.heappush(min_heap, 3)
heapq.heappush(min_heap, 2)

print(min_heap)
min_value = heapq.heappop(min_heap)
print(min_heap)


[1, 2, 7, 4, 3]
[2, 3, 7, 4]
