In [ ]:
# https://github.com/teddylee777/machine-learning

In [1]:
from IPython.display import Image

Image(url='https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMTM0/MDAxNTkwMzc4MTY4MDQy.iOzxIfhew8Bsto7uqNW3QYj-k9bysF775jXYLECD6bwg.uMJ87NPURvklkXF2TXFnygaSnc32erHm_mXbnKgvO24g.PNG.nabilera1/image.png?type=w800')

In [3]:
import pandas as pd

pd.set_option('display.float_format', lambda x:'.1f' %x)
data = pd.read_csv('http://bit.ly/ld-sample-idol', index_col='순위')
data

이름     그룹      소속사  성별        생년월일   키 혈액형   브랜드평판지수
순위                                                        
1     지민  방탄소년단      빅히트  남자  1995-10-13 .1f   A  10523260
2   지드래곤     빅뱅       YG  남자  1988-08-18 .1f   A   9916947
3   강다니엘    NaN      커넥트  남자  1996-12-10 .1f   A   8273745
4      뷔  방탄소년단      빅히트  남자  1995-12-30 .1f  AB   8073501
5     화사    마마무      RBW  여자  1995-07-23 .1f   A   7650928
6     정국  방탄소년단      빅히트  남자  1997-09-01 .1f   A   5208335
7     민현   뉴이스트     플레디스  남자  1995-08-09 .1f   O   4989792
8     소연    아이들       큐브  여자  1998-08-26 .1f   B   4668615
9      진  방탄소년단      빅히트  남자  1992-12-04 .1f   O   4570308
10   하성운     핫샷  스타크루이엔티  남자  1994-03-22 .1f   A   4036489
11    태연   소녀시대       SM  여자  1989-03-09 .1f   A   3918661
12   차은우   아스트로     판타지오  남자  1997-03-30 .1f   B   3506027
13    백호   뉴이스트     플레디스  남자  1995-07-21 .1f  AB   3301654
14    JR   뉴이스트     플레디스  남자  1995-06-08 .1f   O   3274137
15    슈가  방탄소년단      빅히트  남자  1993-03-09 .1f   O   2925442

In [1]:
import torch
import numpy as np
torch.__version__

'1.13.1'

In [2]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [6]:
t1 = torch.from_numpy(arr)
t1
t2 = torch.as_tensor(arr)
t2
t3 = torch.tensor(arr)
t3

tensor([0, 1, 2, 3, 4])

In [9]:
a = torch.arange(5)
print(a)
b = torch.linspace(2,10,5)
print(b)

tensor([0, 1, 2, 3, 4])
tensor([ 2.,  4.,  6.,  8., 10.])
